### PR TITLE
Map widget added showing current location.

### PR DESCRIPTION
**Pull request by nelsontloz**
@SmilingKat please take a look.

### CODE REVIEW

**Comment by KatjaRademacher** [comment]
Hi @nelsontloz ,

I seem to be having some trouble getting the current location. 

My steps: 
1. start the application with npm start
2. On my phone, I enabled the location
3. I opened Chrome and went to the IP of my PC with port 3000
4. This shows me the web app on the phone in the browser but the marker is set to 0,0 as the position

Any chance you could help, what I need to do?

Thanks, 
Katja

**Comment by gkemp94** [comment]
@SmilingKat I tried it and it looks good. You might have blocked location on localhost at some point. I also testing multiple locations and looks good. It doesn't refresh on location change, (no polling), but I don't think that's necessary, just an addition of a refresh button would suffice.

**Review by gkemp94 — APPROVED** [review]
Looks good

**Comment by nelsontloz** [comment]
Hi Kajta, I figured it out, which browser are you using?
I found it:
"Something to note is that as from Chrome version 50.0, Geo Location is
only supported over a secure connection that implements an SSL layer
(HTTPS). Geo Location will not work over non-secure origins such as HTTP."
please read:
https://developers.google.com/web/fundamentals/native-hardware/user-location/

The browser allows to get location without HTTPS only on "localhost" or
"127.0.0.1".
PD: I have set up a web server with https, if you want I could deploy my
branch there, please let me know.

Finally here you have some screen-captures from my cellphone:

With HTTPS (self signed certs), browser allows to get location
[image: Screenshot_2018-10-18-20-21-10-795_com.android.chrome.png]

Without HTTPS, browser do not allow to get location
[image: Screenshot_2018-10-18-20-32-06-885_com.android.chrome.png]

Regards,
Nelson

**Pull request merged**
